### ISSUE TITLE
@genre

### ISSUE THREAD

**Issue by Richard-Frost** [learn-co-curriculum/ruby-objects-has-many-readme#14]
Hi i'm not sure if there's something missing or not but it feels like @genre was used but never actually added.  maybe it was just implied?  not sure but just wanted to bring it up.  
<img width="940" alt="screen shot 2016-01-31 at 3 48 42 pm" src="https://cloud.githubusercontent.com/assets/14037328/12706113/80e3849e-c832-11e5-9441-cac187364954.png">

**Comment by AnnJohn** [comment]
hi @Richard-Frost yes think you're right. We'll look at this soon and update. Thanks.
