### ISSUE TITLE
change from number `99` to words `ninetynine`

### ISSUE THREAD

**Issue by fossbender** [learn-co-curriculum/ruby-objects-has-many-readme#16]
In the `RELATING OBJECTS WITH "BELONGS TO" AND "HAS MANY"` section, the `99` should be changed to `nintynine`

`99`_problems = Song.new("99 Problems", "rap")
crazy_in_love = Song.new("Crazy in Love", "pop")

jay_z.add_song(`99`_problems)

**Comment by AnnJohn** [comment]
thanks @fossbender we'll fix this very soon.

**Comment by victhevenot** [comment]
Thanks so much!
