### ISSUE TITLE
change way to add song

### ISSUE THREAD

**Issue by JeffKatzy** [learn-co-curriculum/ruby-objects-has-many-readme#30]
Instead, just create with Song.create(artist: self), or something like that

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#38.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hey @JeffKatzy,

After reviewing this lesson - in its current position as one of the first lessons on OO relationships, I think it is better to keep it as is. We are, however, looking at ways to further connect this section of content to the later ORM / ActiveRecord conventions and will be creating content for later in this section to address this.

Hope you are well!
