### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/ruby-objects-has-many-readme#38]
PROBLEM: Improve the way we add songs. See issue #30.
NOTIFY: @JeffKatzy

**Comment by maxwellbenton** [comment]
No action. After review of current lesson and current position, including `create` seems to advanced. Will note this for the mod 1 clean up as a possible bridge that is needed between this early OO relationship content and the later, more SQL like designs that are closer to the ORMs/ActiveRecord content
