### ISSUE TITLE
The last sentence makes no sense

### ISSUE THREAD

**Issue by jackrobinrye** [learn-co-curriculum/ruby-objects-has-many-readme#39]
The last sentence of this lesson makes no sense:

"These are only a few of the ways in which you can extend, or build on, the foundational has many and belongs to associations."

**Comment by maxwellbenton** [comment]
Hi @jackrobinrye,

We've updated the conclusion of this lesson and removed this sentence, which should resolve this issue.

Thank you for opening this issue and providing feedback!
